#pragma once

#include <string>

#include "Game/GameManager.h"
#include "Game/SnowAttack.h"
#include "Game/SnowEnergy.h"

// One participant in a match: their Tetris session (GameManager) plus
// snow-battle state. Player doesn't know about its opponent — Match wires
// line-clear events to attacks and routes incoming ones here.
class Player
{
public:
    explicit Player(std::string name);

    const std::string& name() const { return m_name; }

    GameManager& gameManager() { return m_gameManager; }
    const GameManager& gameManager() const { return m_gameManager; }

    // Snow energy generated by this player's own line clears so far. Purely
    // a tracked/displayable stat for now — attacks fire immediately on
    // clear rather than being banked and spent (see Match).
    int snowEnergy() const { return m_snowEnergy.total(); }
    void addSnowEnergy(int amount) { m_snowEnergy.add(amount); }

    // Applies an incoming attack's garbage rows to this player's board.
    // Returns false if it caused the board to overflow (game over).
    bool receiveAttack(const SnowAttack& attack);

    void reset();

private:
    std::string m_name;
    GameManager m_gameManager;
    SnowEnergy m_snowEnergy;
};
